//! This crate contains a framework for low-degree tests (LDTs).

#![no_std]
#![deprecated]

mod naive;

pub use naive::*;

extern crate alloc;

use p3_field::{Field, TwoAdicField};
use p3_matrix::Matrix;
use p3_matrix::dense::RowMajorMatrix;

/// Perform low-degree extensions; both original and extended domain are undefined,
/// but must remain consistent across calls with the same input height.
pub trait UndefinedLde<Val, In>
where
    Val: Field,
    In: Matrix<Val>,
{
    type Out: Matrix<Val>;

    fn lde_batch(&self, polys: In, extended_height: usize) -> Self::Out;
}

/// Perform low-degree extensions over (possibly trivial) cosets of multiplicative subgroups of domain.
pub trait TwoAdicLde<Val>
where
    Val: TwoAdicField,
{
    /// Given a batch of polynomials, each defined by 2^k evaluations over the subgroup generated
    /// by `EF::primitive_root_of_unity(k)`, evaluate over the (possibly trivial) coset `shift H`,
    /// where H is the subgroup generated by `EF::primitive_root_of_unity(k + added_bits)`.
    fn lde_batch(&self, polys: RowMajorMatrix<Val>, added_bits: usize) -> RowMajorMatrix<Val>;
}

/// A specialization of `TwoAdicLde` to evaluate polynomials over a multiplicative subgroup of domain,
/// in other words, a trivial coset thereof.
pub trait TwoAdicSubgroupLde<Val>: TwoAdicLde<Val>
where
    Val: TwoAdicField,
{
}

/// A specialization of `TwoAdicLde` to evaluate polynomials over a nontrivial coset of a multiplicative
/// subgroup of the domain.
pub trait TwoAdicCosetLde<Val>: TwoAdicLde<Val>
where
    Val: TwoAdicField,
{
    fn shift(&self, lde_bits: usize) -> Val;
}
